apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gin-sample
      type: postgres
  serviceName: postgres
  template:
    metadata:
      name: postgres
      labels:
        app: gin-sample
        type: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:12.3
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: storage
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim
