apiVersion: v1
kind: Service
metadata:
  name: db-svc
  labels:
    app: gin-sample
    type: postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: gin-sample
    type: postgres
