apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: gin-sample
    type: postgres
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
